version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  zookeeper:
    image: 'zookeeper:3.6.3'
    container_name: 'zookeeper'
    ports:
      - '2181:2181'
    networks:
      - kafka-net
  kafka:
    image: 'confluentinc/cp-kafka:6.2.0'
    container_name: 'kafka'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net
      
volumes:
  mongodb_data_container:
  
networks:
  kafka-net:
    driver: bridge